project_id = "safetyops"

[auth]
site_url = "https://loufish727.github.io/SafetyOps/"
additional_redirect_urls = ["https://loufish727.github.io/SafetyOps/"]
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
secure_password_change = true

[functions.sign-form-file]
verify_jwt = true
